//go:build integration

package integration_test

import (
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"

	"github.com/codeswhat/sockguard/internal/config"
)

// tecnativaCompatEnvVars is the full set of env vars sockguard's Tecnativa
// compatibility layer reads. The test snapshots and clears them at the start
// of each preset so a stale shell value (e.g. CONTAINERS=1 carried over from
// a Tecnativa migration) cannot bleed into another preset's expected
// ruleset. It mirrors the unexported list in internal/config/compat.go; the
// duplication is deliberate — keeping the integration tier independent of
// the package's private surface.
var tecnativaCompatEnvVars = []string{
	"AUTH", "BUILD", "COMMIT", "CONFIGS", "CONTAINERS",
	"DISTRIBUTION", "EVENTS", "EXEC", "GRPC", "IMAGES",
	"INFO", "NETWORKS", "NODES", "PING", "PLUGINS",
	"POST", "SECRETS", "SERVICES", "SESSION", "SWARM",
	"SYSTEM", "TASKS", "VERSION", "VOLUMES",
	"ALLOW_START", "ALLOW_STOP", "ALLOW_RESTART",
	"ALLOW_RESTARTS", "ALLOW_PAUSE", "ALLOW_UNPAUSE", "ALLOW_CREATE",
	"ALLOW_EXEC", "ALLOW_KILL", "ALLOW_DELETE", "ALLOW_PRUNE",
}

// presetExpectation pins one (method, path) request and whether the proxy
// chain should allow it under the preset's generated ruleset.
type presetExpectation struct {
	method      string
	path        string
	wantAllowed bool
}

// TestTecnativaPresetConformance fires a representative request matrix at a
// sockguard chain whose rules were generated by config.ApplyCompat from a
// preset's env vars, with the proxy pointed at a real dockerd. Each preset
// asserts which requests survive the rule layer (the proxy did not catch-all
// deny) and which the catch-all blocks — end-to-end against the same daemon
// a production deployment would use.
//
// Scope is the rule layer: path and method matching, plus the section /
// granular-POST / POST-broadens-reads interactions in compat.go. Body
// inspectors are out of scope and have their own coverage:
//
//   - POST /containers/*/exec is not asserted because sockguard's exec
//     inspector denies by default (no allowed_commands allowlist), independent
//     of the rule that admits the path;
//   - POST /containers/create requests use a body with no Privileged, no
//     NetworkMode=host, and none of the always-denied HostConfig fields, so
//     the container-create body inspector passes and the assertion measures
//     only the rule layer.
//
// A deny that reaches the catch-all is identified by status 403 plus the
// catch-all's reason text ("no matching allow rule"); any other 403 (a
// body-inspector verdict, an upstream daemon 403) does not satisfy the
// catch-all assertion and the test fails loudly with the response body.
func TestTecnativaPresetConformance(t *testing.T) {
	socketPath := dockerSocketForIntegration(t)

	presets := []struct {
		name   string
		env    map[string]string
		expect []presetExpectation
	}{
		{
			// Traefik-style minimal Docker watcher: read containers, nothing else.
			name: "containers-read",
			env:  map[string]string{"CONTAINERS": "1"},
			expect: []presetExpectation{
				{http.MethodGet, "/_ping", true},
				{http.MethodGet, "/version", true},
				{http.MethodGet, "/events", true},
				{http.MethodGet, "/containers/json", true},
				{http.MethodHead, "/containers/json", true},
				{http.MethodGet, "/containers/abc/json", true},
				{http.MethodGet, "/images/json", false},
				{http.MethodGet, "/networks", false},
				{http.MethodPost, "/containers/abc/start", false},
				{http.MethodPost, "/containers/create", false},
				{http.MethodDelete, "/containers/abc", false},
			},
		},
		{
			// Portainer-style broad read across the resource sections.
			name: "portainer-broad-read",
			env: map[string]string{
				"CONTAINERS": "1",
				"IMAGES":     "1",
				"NETWORKS":   "1",
				"VOLUMES":    "1",
			},
			expect: []presetExpectation{
				{http.MethodGet, "/containers/json", true},
				{http.MethodGet, "/images/json", true},
				{http.MethodGet, "/networks", true},
				{http.MethodGet, "/volumes", true},
				{http.MethodGet, "/services", false},
				{http.MethodGet, "/nodes", false},
				{http.MethodPost, "/containers/abc/start", false},
			},
		},
		{
			// Drydock-style: read containers and start them; nothing else mutating.
			name: "containers-and-start",
			env: map[string]string{
				"CONTAINERS":  "1",
				"ALLOW_START": "1",
			},
			expect: []presetExpectation{
				{http.MethodGet, "/containers/json", true},
				{http.MethodPost, "/containers/abc/start", true},
				{http.MethodPost, "/containers/abc/stop", false},
				{http.MethodPost, "/containers/abc/kill", false},
				{http.MethodPost, "/containers/create", false},
				{http.MethodDelete, "/containers/abc", false},
			},
		},
		{
			// ALLOW_RESTARTS bundles kill+restart+stop — but NOT start (start
			// requires its own ALLOW_START). Pin that explicitly so a future
			// edit to compat.go's granular rule table that quietly folds /start
			// in would fail this case.
			name: "restarts-flag-excludes-start",
			env: map[string]string{
				"CONTAINERS":     "1",
				"ALLOW_RESTARTS": "1",
			},
			expect: []presetExpectation{
				{http.MethodPost, "/containers/abc/kill", true},
				{http.MethodPost, "/containers/abc/restart", true},
				{http.MethodPost, "/containers/abc/stop", true},
				{http.MethodPost, "/containers/abc/start", false},
				{http.MethodPost, "/containers/abc/pause", false},
				{http.MethodPost, "/containers/create", false},
				{http.MethodDelete, "/containers/abc", false},
			},
		},
		{
			// Granular create + delete without any of the lifecycle verbs.
			name: "create-and-delete",
			env: map[string]string{
				"CONTAINERS":   "1",
				"ALLOW_CREATE": "1",
				"ALLOW_DELETE": "1",
			},
			expect: []presetExpectation{
				{http.MethodPost, "/containers/create", true},
				{http.MethodDelete, "/containers/abc", true},
				{http.MethodPost, "/containers/abc/start", false},
				{http.MethodPost, "/containers/abc/stop", false},
			},
		},
		{
			// POST=1 broadens every read rule's methods to "*", so a single
			// section flag now admits every verb on that section.
			name: "containers-full-post",
			env: map[string]string{
				"CONTAINERS": "1",
				"POST":       "1",
			},
			expect: []presetExpectation{
				{http.MethodGet, "/containers/json", true},
				{http.MethodPost, "/containers/create", true},
				{http.MethodPost, "/containers/abc/start", true},
				{http.MethodDelete, "/containers/abc", true},
				{http.MethodPut, "/containers/abc/rename", true},
				{http.MethodPost, "/images/create", false},
				{http.MethodGet, "/networks", false},
			},
		},
		{
			// Override one of the defaultAllow=true sections explicitly.
			// PING=0 must drop the default /_ping allow without affecting
			// the other defaults.
			name: "ping-disabled",
			env: map[string]string{
				"CONTAINERS": "1",
				"PING":       "0",
			},
			expect: []presetExpectation{
				{http.MethodGet, "/_ping", false},
				{http.MethodGet, "/version", true},
				{http.MethodGet, "/events", true},
				{http.MethodGet, "/containers/json", true},
			},
		},
		{
			// A different section family: a swarm orchestrator that reads
			// swarm/nodes/tasks/services but cannot mutate anything.
			name: "swarm-orchestrator-read",
			env: map[string]string{
				"SWARM":    "1",
				"NODES":    "1",
				"TASKS":    "1",
				"SERVICES": "1",
			},
			expect: []presetExpectation{
				{http.MethodGet, "/swarm", true},
				{http.MethodGet, "/nodes", true},
				{http.MethodGet, "/tasks", true},
				{http.MethodGet, "/services", true},
				{http.MethodGet, "/containers/json", false},
				{http.MethodPost, "/services/create", false},
			},
		},
	}

	for _, preset := range presets {
		t.Run(preset.name, func(t *testing.T) {
			// Hermetic env scope: snapshot the shell's compat-relevant vars,
			// clear them so a stray export cannot influence the ruleset, then
			// set the preset's. Cleanup restores whatever the shell had.
			restoreEnv := snapshotCompatEnv()
			t.Cleanup(restoreEnv)
			for _, key := range tecnativaCompatEnvVars {
				os.Unsetenv(key)
			}
			for k, v := range preset.env {
				os.Setenv(k, v)
			}

			cfg := config.Defaults()
			if !config.ApplyCompat(&cfg, slog.New(slog.NewTextHandler(io.Discard, nil))) {
				t.Fatalf("ApplyCompat did not activate for preset %q with env %v",
					preset.name, preset.env)
			}

			handler := newIntegrationProxyHandler(t, socketPath, cfg.Rules)

			for _, exp := range preset.expect {
				runPresetExpectation(t, handler, preset.name, exp)
			}
		})
	}
}

// snapshotCompatEnv records the current value (or unset state) of every
// tecnativaCompatEnvVar and returns a closure that restores them. The
// integration tier never assumes a clean shell — a contributor running the
// suite locally may have exports left over from a Tecnativa migration, and
// CI may inject vars too.
func snapshotCompatEnv() func() {
	type snapshotEntry struct {
		value string
		set   bool
	}
	snapshot := make(map[string]snapshotEntry, len(tecnativaCompatEnvVars))
	for _, key := range tecnativaCompatEnvVars {
		val, ok := os.LookupEnv(key)
		snapshot[key] = snapshotEntry{value: val, set: ok}
	}
	return func() {
		for key, entry := range snapshot {
			if entry.set {
				os.Setenv(key, entry.value)
			} else {
				os.Unsetenv(key)
			}
		}
	}
}

// runPresetExpectation drives one request through the preset's handler chain
// and asserts whether the proxy's catch-all denied it, matching the preset's
// declared expectation. A "denial" here is specifically the catch-all rule
// reason — any other 403 (body inspector, upstream) is reported back, so a
// test that thinks it's checking the rule layer but actually trips a body
// inspector fails loudly with the daemon's response body.
func runPresetExpectation(t *testing.T, handler http.Handler, presetName string, exp presetExpectation) {
	t.Helper()

	var body io.Reader
	headers := map[string]string{}
	switch {
	case exp.method == http.MethodPost && exp.path == "/containers/create":
		// Minimal body that passes sockguard's container-create inspector
		// (no Privileged, no NetworkMode=host, none of the always-denied
		// HostConfig fields). The image is unlikely to exist, so the daemon
		// returns a 4xx — the proxy forwards regardless, the status is not
		// 403, and the "allowed" assertion holds without creating a container.
		body = strings.NewReader(`{"Image":"qa2-preset-conformance-noimage:nonexistent","Cmd":["true"]}`)
		headers["Content-Type"] = "application/json"
	case exp.method == http.MethodPost && exp.path == "/services/create":
		// Only used as a denied case (the swarm preset does not include any
		// ALLOW_* nor POST=1). A skeletal body is enough — the catch-all
		// rejects before the body inspector runs.
		body = strings.NewReader(`{"Name":"qa2-test","TaskTemplate":{}}`)
		headers["Content-Type"] = "application/json"
	}

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(exp.method, exp.path, body)
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	handler.ServeHTTP(rec, req)

	deniedByCatchAll := rec.Code == http.StatusForbidden &&
		strings.Contains(rec.Body.String(), "no matching allow rule")

	if exp.wantAllowed {
		if deniedByCatchAll {
			t.Fatalf("preset %q: %s %s was catch-all denied but the preset should admit it (status %d, body %s)",
				presetName, exp.method, exp.path, rec.Code, clipResponseBody(rec.Body.String()))
		}
		return
	}

	if !deniedByCatchAll {
		t.Fatalf("preset %q: %s %s should be catch-all denied but was not (status %d, body %s)",
			presetName, exp.method, exp.path, rec.Code, clipResponseBody(rec.Body.String()))
	}
}

// clipResponseBody bounds a captured body for inclusion in a failure message.
func clipResponseBody(body string) string {
	const max = 200
	if len(body) > max {
		return body[:max] + "…"
	}
	return body
}
