apiVersion: v1
kind: Service
metadata:
  name: {{ include "sockguard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sockguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sockguard.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
