export type Milestone = {
  version: string;
  title: string;
  emoji: string;
  status: "released" | "next" | "planned";
  items: string[];
};

export const roadmap: Milestone[] = [
  {
    version: "v1.0.0",
    title: "Foundation",
    emoji: "✅",
    status: "released",
    items: [
      "Default-deny proxy: method + path filtering with percent-decoded path canonicalization",
      "Request body inspection (container, exec, image, build, volume, network, secret, config, service, swarm, node, plugin)",
      "Mutual TLS 1.3 enforced on all non-loopback TCP listeners",
      "Signed policy bundles (cosign keyed + keyless, Rekor inclusion proof)",
      "Container image trust (cosign verify before /containers/create, enforce / warn modes)",
      "Owner label isolation for workload and control-plane resources",
      "Client ACL primitives: CIDR, mTLS cert selectors, unix peer credentials",
      "Named client profiles with per-profile rollout modes (enforce / warn / audit)",
      "12 bundled policy presets: drydock, Traefik, Portainer, Watchtower, CIS Docker Benchmark, GitHub Actions runner, GitLab Runner, and more",
    ],
  },
  {
    version: "v1.1.0",
    title: "Security Hardening",
    emoji: "🔒",
    status: "released",
    items: [
      "21 HIGH + MEDIUM security findings fixed across a full multi-axis audit",
      "Image-trust wired end-to-end — cosign signatures verified against resolved manifest digest, TOCTOU sealed",
      "Plugin install, service create/update, and docker load bypass vectors closed",
      "Ownership isolation: bounded LRU caches, negative-cache closed, image /get gated",
      "Response redaction gaps closed (Mounts source, PreviousSpec, MaskedPaths/ReadonlyPaths)",
      "Constant-time SPKI pin comparison; gzip-bomb guards on build and plugin paths",
      "QA harness: proxy-vs-daemon differential, mTLS edge-case suite, fuzz targets, goroutine-leak soak",
    ],
  },
  {
    version: "v1.2.0",
    title: "Resilience & Observability",
    emoji: "📊",
    status: "released",
    items: [
      "Opt-in upstream readiness probe (GET /containers/json health check — returns 503 on a wedged daemon)",
      "upstream.request_timeout — 504 Gateway Timeout on hung proxied finite requests",
      "Upstream response-header timeout hardened across all side-channel transports",
      "drydock preset: allowlisted runc runtime to fix update recreate rollbacks",
      "Go toolchain bumped to 1.26.4 — clears two reachable stdlib advisories (GO-2026-5037, GO-2026-5039)",
    ],
  },
  {
    version: "v1.3.0",
    title: "Posture Hardening",
    emoji: "🛡️",
    status: "released",
    items: [
      "Swarm service create/update enforces container-create identity/privilege rails (non-root, no-new-privileges, readonly rootfs, drop ALL)",
      "Zero-padded UID bypass sealed — '00', '000', '0:0' all parsed numerically as root",
      "Wide-open dedicated admin listener rejected at config validation, not just warned",
      "Admin endpoint paths normalized before matching — trailing-slash and dot-segment variants closed",
      "signature_path hot-reload wedge fixed — verification reads from candidate config",
      "Non-upgrade hijack responses strip hop-by-hop headers",
      "Multi-arch images cross-compile natively (no QEMU emulation in CI)",
    ],
  },
  {
    version: "v1.4.0",
    title: "Remote Upstreams & Fleet Presets",
    emoji: "🌐",
    status: "released",
    items: [
      "Remote Docker daemon over TCP with mutual TLS and active/passive failover",
      "Ordered endpoint failover — connect failure instantly promotes next endpoint without retry",
      "Portwing presets (portwing.yaml, portwing-with-exec.yaml) and drydock-with-selfupdate.yaml",
      "Drydock preset conformance audit — runc runtime, multi-network connect, self-update finalize exec all fixed",
      "Swarm service seccomp/AppArmor confinement rails (deny_unconfined_seccomp, deny_unconfined_apparmor)",
      "Rate-limit token bucket: allocation-free hot path, 0 allocs/0 B per op at ~36 ns",
      "Enforced CI coverage floor (96%) with Qlty Cloud reporting",
      "v1.4.1–v1.4.4 security patches: reachable TLS and dependency advisories cleared, case-varied JSON and log-injection paths closed, embedded owner dependencies freshly authorized, plugin inspection made fail-closed, registry-push exfiltration gated, and Vercel/Helm defaults hardened",
    ],
  },
  {
    version: "v1.5.0",
    title: "Safer Defaults & Namespace Hardening",
    emoji: "🔧",
    status: "released",
    items: [
      "upstream.request_timeout now defaults to 60s (was unlimited); 'off' restores unlimited",
      "ownership.allow_cross_owner_namespace_sharing defaults to false — cross-owner container:<id> namespace joins denied by default when ownership.owner is set",
      "Namespace-sharing gate: restrict_namespace_sharing + allowed_namespace_sharing_containers gate container:<id> joins across NetworkMode/PidMode/IpcMode/UsernsMode; deny_namespace_path_mode blocks raw ns:<path> on NetworkMode only",
      "allow_host_cgroupns (default false) extends the host-mode denials to HostConfig.CgroupnsMode — the one host namespace the allow_host_* family didn't previously gate",
      "require_cpu_limit_hard — opt-in hard CPU-time cap (NanoCpus/CpuQuota), independent of require_cpu_limit",
      "Exec Env policy — name allow/denylisting plus exact allowed_env_values pinning for security-sensitive entries",
      "New presets: portwing-with-compose.yaml, drydock-with-compose.yaml, plus a tri-tool compose example",
      "Helm chart: pod-level podSecurityContext",
      "Security-pass fixes merged forward: fresh embedded-resource ownership checks, registry-push exfiltration gate, browser headers, non-root/seccomp Helm defaults, structured-log sanitization, fail-closed plugin inspection, and patched dependency graphs",
      "Promoted to stable after rc.1/rc.2 field exposure and clean rc.3 CI, security, artifact, signature, and published-image validation",
      "Config Viper-default registration generated by reflection off Defaults()",
    ],
  },
  {
    version: "v1.5.1",
    title: "Integration & Packaging Fixes",
    emoji: "🔧",
    status: "released",
    items: [
      "Fresh named-volume Unix-socket deployments start under UID/GID 65532 without manual ownership repair",
      "Portwing examples use the published GHCR image and a portable OpenSSL token command",
      "Tri-tool local demo binds dashboards to loopback and explicitly configures drydock authentication behavior",
      "Published-image compatibility audit documents the remote update-trigger boundary across Portwing Standard and Edge modes",
      "Competitor review refreshes comparison facts and commits the evidence-backed v1.6 roadmap",
    ],
  },
  {
    version: "v1.5.2",
    title: "Security, Integration & Distribution Fixes",
    emoji: "🔧",
    status: "released",
    items: [
      "Image-type Mounts entries on containers/create and services/create/update now enforce image_trust before forwarding, closing an unverified-image-filesystem bypass",
      "redact_network_topology now also strips the Engine API 1.53 network-inspect Status field",
      "Homebrew distribution through CodesWhat/homebrew-tap for native macOS and Linux installs of stable releases",
      "New docker-compose.edge-exec.yml tri-tool variant wires Portwing Edge Mode to drydock over Ed25519 key-based auth for interactive exec",
      "Portwing presets set deny_verbosity: verbose so sockguard's detailed denial reasons reach Portwing and drydock",
      "Nightly integration CI no longer breaks on Docker Hub busybox re-tags — the pre-pull step reads the pinned digest straight from the test helper constant",
      "Website overview matrix now exposes the multiple-listener comparison alongside the Podman gap",
    ],
  },
  {
    version: "v1.6.0",
    title: "Runtime Compatibility & Policy Mediation",
    emoji: "🧭",
    status: "released",
    items: [
      "Podman support: preserve Docker-compatible API behavior and add explicit, default-deny policy coverage for the native /libpod namespace, including pod lifecycle operations",
      "Multiple independently configured main listeners (Unix and/or TCP), with listener-scoped TLS and client-profile boundaries",
      "Declarative safe admission mutations, starting with mandatory label injection and image-reference remapping; every mutated body is re-inspected before forwarding",
      "Published-image conformance matrix for Sockguard + Portwing + Drydock across standard and edge transports; remote update claims stay gated on implemented watcher/trigger contracts",
      "Docker Engine API 1.55 and current Compose/BuildKit conformance, replacing assumptions around the now-deprecated /session and /grpc endpoints with a verified fail-closed transport model",
      "Close the remaining resource-policy parity gaps: revalidate hard resource caps on container update and add swarm-service CPU-limit requirements",
    ],
  },
  {
    version: "v1.7.0",
    title: "BuildKit Mediation & Policy Narrowing",
    emoji: "🔬",
    status: "released",
    items: [
      "BuildKit gRPC mediation: terminate the hijacked session/gRPC tunnel, parse moby.buildkit.v1.Control frames, and apply policy to solve requests, secret/SSH forwarding, and file-sync sessions instead of the current all-or-nothing acknowledgment",
      "request_body.network.endpoint_config.* per-field gates (allow_static_addressing, allow_link_local_ips, allow_mac_pinning, allow_gw_priority, allow_aliases) for endpoint settings on both network connect and container-create, so benign endpoint settings no longer require also allowing static-IP/MAC address pinning; allow_endpoint_config: true remains the broad whole-object override",
    ],
  },
  {
    version: "v1.7.1",
    title: "CI/CD Security Gating",
    emoji: "🔒",
    status: "released",
    items: [
      "Four PR-gate gaps closed: Dependency Review, Gitleaks secret scanning, and Actionlint workflow linting all now run and block on every PR; Grype image scanning moves into the required Docker Build job",
      "Release binaries ship a CycloneDX SBOM per archive; the SLSA claim is qualified to Build L2 with a protected v* tag ruleset",
      "Weekly ZAP baseline passive DAST scan covers the static getsockguard.com marketing site and docs",
      "Cookieless PostHog analytics replaces Vercel Analytics across the marketing site and docs — no cookies, no consent banner",
      "Branch protection required contexts grow from 9 to 17; all CI job names drop decorative emoji since check names are matched by exact string",
      "CI runners pin to ubuntu-24.04 and harden-runner begins moving off blanket audit-mode egress",
    ],
  },
  {
    version: "v1.7.2",
    title: "Release Signing & Conformance Fixes",
    emoji: "🔧",
    status: "released",
    items: [
      "The publish run failed while signing checksums.txt against cosign v3's new bundle-format defaults, so this tag shipped no artifacts, release, or images; v1.7.3 carries its content",
      "Per-platform release archives are now cosign-signed and carry SLSA build provenance, closing the gap where only the source tarball was signed and attested",
      "The tri-tool conformance matrix's store-sync poll reads drydock's versioned /api/v1 endpoints and stops swallowing its own errors",
      "current-standard and current-edge conformance rows now resolve sockguard to the newest published stable release instead of a stale floor pin",
      "The lockfile-dedupe pre-push hook no longer misreports a stale node_modules as lockfile drift",
      "release-cut.yml's CI gate no longer times out before CI: Verify can finish",
      "Biome now lints and formats the 38 tracked .mjs files it had never been checking",
    ],
  },
  {
    version: "v1.7.3",
    title: "Cosign v3 Signing Fix",
    emoji: "🔏",
    status: "released",
    items: [
      "Fixes the v1.7.2 publish failure: cosign v3 defaults to the new sigstore bundle format and signing-config flow, which made it ignore the signs: blocks' output flags and demand an unset --bundle path",
      "Both signs: blocks now pass --new-bundle-format=false and --use-signing-config=false, restoring the legacy .sig/.pem output the docs and QA-6 verification rely on",
      "Every cosign-installer step pins cosign-release v3.1.3 so CI runs the exact binary the flags were verified against",
    ],
  },
  {
    version: "v1.7.4",
    title: "First-Party Star Chart & Release Monitor",
    emoji: "📈",
    status: "released",
    items: [
      "The star-history chart is a committed first-party SVG pair regenerated at each release cut, replacing the dead Warpchart embed, whose domain is out of the site CSP",
      "A daily Main Is Released monitor asserts main's HEAD points at a release tag, so default-branch scanners always describe the shipped version",
    ],
  },
  {
    version: "v1.7.5",
    title: "Security Patch: Filter Bypass Closures",
    emoji: "🔒",
    status: "released",
    items: [
      "Swarm services can no longer reach the host network through TaskTemplate.Networks, closing a silent bypass of allow_host_network: false",
      "Three build-time RUN-instruction gate bypasses are closed: duplicate-Dockerfile context tars, upload-session contexts, and frontend-less raw-LLB Solves — the latter now denied outright (any ExecOp, or any op that fails to decode) when allow_run_instructions is false",
      "Cross-owner image-attestations access and two stale identity caches are closed, and image-trust verification rejects cross-repository signature transplants",
      "Grype now scans the published multi-arch image per platform, on release and weekly, instead of only from-source CI builds",
    ],
  },
  {
    version: "v2.0.0",
    title: "Pinned Policy Trust & Whole-App Hardening",
    emoji: "🛡️",
    status: "released",
    items: [
      "Signed policies pin keyed or keyless trust in a separate bootstrap file selected out of band, with bounded YAML and bundle inputs; candidate YAML can no longer select, replace, or disable its own trust",
      "Native Podman builds gain fail-closed primary/additional-context controls, host-write acknowledgments, Dockerfile inspection, and owner-label stamping",
      "BuildKit state is isolated by trusted caller principal, selected profile, and session ID, with atomic admission, bounded persistent IDs, expiring upload grants, and bounded upgrade handshakes",
      "Unix socket ownership, response filtering, keyword-named resource authorization, metric cardinality, and inspected-body deadlines are hardened across the composed proxy",
      "Helm supports separate candidate, trust, and signature objects with signed listener settings and render-time trust-boundary validation",
      "Release archives and checksums use sigstore bundles; images are signed and verified by digest, with verified publication metadata and persisted provenance records",
    ],
  },
  {
    version: "v2.1.0",
    title: "BuildKit RUN-Instruction Coverage",
    emoji: "🧩",
    status: "next",
    items: [
      "Extend the shipped BuildKit gRPC mediation foundation: v2.0.0's bounded-depth LLB walk denies any ExecOp, and any op that fails to decode, in frontend-less Solves when allow_run_instructions is false — a blanket refusal; the remaining work is real per-instruction mediation of raw-LLB and third-party frontends so RUN-equivalent ops can be inspected and selectively allowed instead of refused wholesale",
    ],
  },
];
