import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

function walkFiles(root) {
  if (!existsSync(root)) return [];
  const files = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const target = join(root, entry.name);
    if (entry.isDirectory()) files.push(...walkFiles(target));
    else if (entry.isFile()) files.push(target);
  }
  return files;
}

function routeSegments(file, root) {
  const segments = relative(root, file).split(sep);
  const filename = segments.pop();
  const stem = filename.slice(0, -extname(filename).length);
  if (stem !== "page" && stem !== "index") segments.push(stem);
  return segments.filter((segment) => segment && !/^\(.+\)$/u.test(segment));
}

export function collectAnalyticsRoutes({ repoRoot }) {
  const resolvedRepoRoot = fileURLToPath(repoRoot);
  const websiteRoot = join(resolvedRepoRoot, "website", "src", "app");
  const docsRoot = join(resolvedRepoRoot, "docs", "content", "docs");
  const routes = new Set();

  for (const file of walkFiles(websiteRoot)) {
    if (!file.endsWith(`${sep}page.tsx`)) continue;
    const segments = routeSegments(file, websiteRoot);
    if (segments.some((segment) => segment.includes("[") || segment.includes("]"))) continue;
    routes.add(segments.length === 0 ? "/" : `/${segments.join("/")}`);
  }

  for (const file of walkFiles(docsRoot)) {
    if (![".md", ".mdx"].includes(extname(file))) continue;
    const segments = routeSegments(file, docsRoot);
    const suffix = segments.length === 0 ? "" : `/${segments.join("/")}`;
    routes.add(`/docs${suffix}`);
  }

  return [...routes].sort();
}

export function renderAnalyticsRouteManifest(routes) {
  const values = routes.map((route) => `  ${JSON.stringify(route)},`).join("\n");
  return `// Generated by scripts/analytics-routes.mjs. Do not edit by hand.\nconst routes = [\n${values}\n] as const;\n\nexport const ANALYTICS_ROUTES: ReadonlySet<string> = new Set(routes);\n`;
}

function run() {
  const repoRoot = pathToFileURL(join(dirname(fileURLToPath(import.meta.url)), "..", sep));
  const expected = renderAnalyticsRouteManifest(collectAnalyticsRoutes({ repoRoot }));
  const targets = [
    join(fileURLToPath(repoRoot), "website", "src", "lib", "analytics-routes.generated.ts"),
    join(fileURLToPath(repoRoot), "docs", "src", "lib", "analytics-routes.generated.ts"),
  ];

  if (process.argv.includes("--check")) {
    for (const target of targets) {
      if (!existsSync(target) || !statSync(target).isFile() || readFileSync(target, "utf8") !== expected) {
        console.error("Analytics route manifests are stale. Run: npm run sync:analytics-routes");
        process.exitCode = 1;
        return;
      }
    }
    return;
  }

  for (const target of targets) writeFileSync(target, expected);
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) run();
