// Generated by scripts/analytics-routes.mjs. Do not edit by hand.
const routes = [
  "/",
  "/compare",
  "/compare/11notes",
  "/compare/cetusguard",
  "/compare/linuxserver",
  "/compare/tecnativa",
  "/compare/wollomatic",
  "/docs",
  "/docs/admin",
  "/docs/cis-docker-benchmark",
  "/docs/configuration",
  "/docs/getting-started",
  "/docs/migration",
  "/docs/multi-host",
  "/docs/observability",
  "/docs/podman",
  "/docs/presets",
  "/docs/roadmap",
  "/docs/security",
  "/docs/verification",
] as const;

export const ANALYTICS_ROUTES: ReadonlySet<string> = new Set(routes);
